### ISSUE TITLE
How to insert the values of the variables token and email inside the program

### ISSUE THREAD

**Issue by Djas2017** [nickalie/CloudflareDDNS#6]
Hi,

We want to have the variables "token" and "email" embedded into the program and avoid sharing them. So, instead of using the config file config.json or entering the variables manually in the command line using the parameters -token= ....  -email= ...., we want to run the program as follow:
 
cloudflareddns-updater -domains=subdomain.domain.tld

Where do we have to put the values of the variables "token" and "email" inside the program to achieve our goal?

Thank you

**Comment by nickalie** [comment]
Hi @Djas2017,
to make it work that way, go to https://github.com/nickalie/CloudflareDDNS/blob/master/src/ng/Config.go#L39 and replace
```
flag.StringVar(&(this.Token), "token", "", "API Key from cloudflare.com account settings")
flag.StringVar(&(this.Email), "email", "", "email from cloudflare.com account settings")
```

with

```
this.Token = "cloudflare-api-token"
this.Email = "cloudflare-email"
```

So Cloudlfare's token and api will be hardcoded.

**Comment by Djas2017** [comment]
Great, thanks for the reply. I have tested it and it's working.
