### ISSUE TITLE
How to restrict the program to only allow updating an existing DNS record (Disallow creating a new record)

### ISSUE THREAD

**Issue by Djas2017** [nickalie/CloudflareDDNS#7]
Hi,

The context:
The program is used by a group of people. Each person is allowed to update a specific DNS record (Example: person01.domain.tld, person02.domain.tld, ...)

In order to avoid creating multiple DNS records (especially typos, ...), how to restrict the program to only allow updating an existing DNS record (Disallow creating a new record)?
Example, when running: 
./cloudflareddns -token=api_key_from_account_settings -email=email_from_account_settings -domains=mysubdomain.domain.com

IF mysubdomain.domain.com exists,
update the DNS record with the new IP (if IP changed)

ELSE 
Display a message "mysubdomain.domain.com does not exist"

Thank you

**Comment by nickalie** [comment]
@Djas2017 
https://github.com/nickalie/CloudflareDDNS/blob/master/src/main.go#L80
Replace
```
fmt.Println("Domain", domain, "with Type", ipType, "doesn't exist. Creating...")
obj, err = api.RecNew(rootDomain, domain, ip, ipType)
if err != nil {
	fmt.Println("Error while creating", domain, ":", err)
	return
}
fmt.Println("Domain", domain, "was created")
```
with
```
fmt.Println("Domain", domain, "with Type", ipType, "doesn't exist. Creating...")
return
```

**Comment by Djas2017** [comment]
Great. Thanks nickalie for your help. This is working fine.
